version: 2.1
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run:
          name: Submodule Pull
          command: git submodule update --init
      - run:
          name: "Workaround `x509: failed to load system roots and no roots provided`"
          command: |
            echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list
            apt-get update
            apt-get install -y ca-certificates
      - run:
          name: Build keymap
          command: |
            make clean
            make keyboard=lily58 keymap=default
      - store_artifacts:
          path: .build/lily58_rev1_default.hex
